# Generated by Django 5.0.14 on 2026-06-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_lat', models.FloatField()),
                ('origem_lon', models.FloatField()),
                ('destino_lat', models.FloatField(blank=True, null=True)),
                ('destino_lon', models.FloatField(blank=True, null=True)),
                ('distancia_km', models.FloatField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando motorista'), ('aceite', 'Aceite pelo motorista'), ('em_curso', 'Em curso'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada'), ('sem_motoristas', 'Sem motoristas disponíveis')], default='aguardando', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('aceite_em', models.DateTimeField(blank=True, null=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Corrida',
                'verbose_name_plural': 'Corridas',
                'db_table': 'corridas',
                'ordering': ['-criada_em'],
            },
        ),
    ]
