# Generated by Django 5.0.14 on 2026-06-16 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corridas', '0001_initial'),
        ('motoristas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='corrida',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corridas_motorista', to='motoristas.motorista'),
        ),
        migrations.AddField(
            model_name='corrida',
            name='passageiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corridas_passageiro', to=settings.AUTH_USER_MODEL),
        ),
    ]
