# Generated by Django 5.2.15 on 2026-06-17 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corridas', '0002_initial'),
        ('motoristas', '0003_alter_motorista_localizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='corrida',
            name='ponto_referencia',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='corrida',
            name='valor_sugerido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='corrida',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando ofertas'), ('aceite', 'Motorista escolhido'), ('em_curso', 'Em curso'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada'), ('sem_motoristas', 'Sem motoristas disponíveis')], default='aguardando', max_length=20),
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipo', models.CharField(choices=[('aceite', 'Aceitou valor sugerido'), ('contra_oferta', 'Contra-oferta')], default='aceite', max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita pelo passageiro'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('corrida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='corridas.corrida')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='motoristas.motorista')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
                'db_table': 'ofertas',
                'ordering': ['valor'],
            },
        ),
    ]
