# Generated by Django 5.2.15 on 2026-06-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corridas', '0003_corrida_ponto_referencia_corrida_valor_sugerido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corrida',
            name='destino_texto',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
