# Generated by Django 5.2.15 on 2026-06-23 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corridas', '0004_add_destino_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='corrida',
            name='origem_texto',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
