# Generated by Django 5.2.15 on 2026-06-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corridas', '0005_corrida_origem_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='corrida',
            name='notificacao_msg_ids',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
