# Generated by Django 5.2.15 on 2026-06-23 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corridas', '0006_notificacao_msg_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pm', 'Passageiro → Motorista'), ('mp', 'Motorista → Passageiro')], max_length=2)),
                ('nota', models.PositiveSmallIntegerField()),
                ('comentario', models.TextField(blank=True, default='')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('avaliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_recebidas', to=settings.AUTH_USER_MODEL)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_feitas', to=settings.AUTH_USER_MODEL)),
                ('corrida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='corridas.corrida')),
            ],
            options={
                'verbose_name': 'Avaliacao',
                'verbose_name_plural': 'Avaliacoes',
                'db_table': 'avaliacoes',
                'ordering': ['-criada_em'],
                'constraints': [models.UniqueConstraint(fields=('corrida', 'tipo'), name='unique_avaliacao_por_tipo')],
            },
        ),
    ]
