# Generated by Django 5.2.15 on 2026-06-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corridas', '0007_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='corrida',
            name='iniciada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
