# Generated by Django 5.2.15 on 2026-06-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corridas', '0008_iniciada_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corrida',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando ofertas'), ('aceite', 'Motorista escolhido'), ('em_curso', 'Em curso'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada'), ('sem_motoristas', 'Sem motoristas disponíveis')], db_index=True, default='aguardando', max_length=20),
        ),
    ]
