# Generated by Django 5.0.14 on 2026-06-16 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motoristas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pix_txid', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('expirada', 'Expirada')], default='pendente', max_length=20)),
                ('paga_em', models.DateTimeField(blank=True, null=True)),
                ('valida_ate', models.DateField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='motoristas.motorista')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'db_table': 'assinaturas',
                'ordering': ['-criada_em'],
            },
        ),
    ]
