# Generated by Django 5.2.15 on 2026-06-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='mp_payment_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
