# Generated by Django 5.0.14 on 2026-06-16 21:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('tipo', models.CharField(choices=[('passageiro', 'Passageiro'), ('motorista', 'Motorista'), ('admin', 'Administrador')], default='passageiro', max_length=20)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('telegram_token', models.CharField(blank=True, max_length=50, null=True)),
                ('telegram_token_expiry', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'utilizadores',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=20, unique=True)),
                ('cidade', models.CharField(max_length=100)),
                ('bairros', models.JSONField(default=list)),
                ('modelo_moto', models.CharField(max_length=80)),
                ('ano_moto', models.PositiveSmallIntegerField()),
                ('cor_moto', models.CharField(max_length=40)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('consumo_km_l', models.FloatField(default=35.0)),
                ('cnh_frente', models.FileField(blank=True, upload_to='documentos/cnh/')),
                ('cnh_verso', models.FileField(blank=True, upload_to='documentos/cnh/')),
                ('antecedentes', models.FileField(blank=True, upload_to='documentos/antecedentes/')),
                ('foto_rosto', models.ImageField(blank=True, upload_to='documentos/fotos/')),
                ('status_cadastro', models.CharField(choices=[('pendente', 'Pendente de análise'), ('em_analise', 'Em análise'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('suspenso', 'Suspenso')], default='pendente', max_length=20)),
                ('motivo_reprovacao', models.TextField(blank=True)),
                ('analisado_em', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=False)),
                ('assinatura_ate', models.DateField(blank=True, null=True)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('telegram_token', models.CharField(blank=True, max_length=50, null=True)),
                ('telegram_token_expiry', models.DateTimeField(blank=True, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=50, null=True)),
                ('ultima_localizacao_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('actualizado_em', models.DateTimeField(auto_now=True)),
                ('analisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motoristas_analisados', to=settings.AUTH_USER_MODEL)),
                ('utilizador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motorista', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'db_table': 'motoristas',
            },
        ),
    ]
