# Generated by Django 5.2.15 on 2026-06-16 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoristas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnderecoFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos_favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enderecos_favoritos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
