# Generated by Django 5.2.15 on 2026-06-17 00:39

from django.db import migrations

try:
    import django.contrib.gis.db.models.fields
    PointField = django.contrib.gis.db.models.fields.PointField
except Exception:
    PointField = None


class Migration(migrations.Migration):

    dependencies = [
        ('motoristas', '0002_enderecofavorito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='localizacao',
            field=PointField(blank=True, null=True, srid=4326),
        ),
    ] if PointField else []
