# Generated by Django 5.2.15 on 2026-06-17 00:39

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motoristas', '0002_enderecofavorito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='localizacao',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
