# Generated by Django 5.2.15 on 2026-06-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoristas', '0003_alter_motorista_localizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='email_confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='email_token',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='email_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
