# Generated by Django 5.2.15 on 2026-06-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoristas', '0004_email_confirmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='enderecofavorito',
            name='numero',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='enderecofavorito',
            name='ponto_referencia',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='enderecofavorito',
            name='rua',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='enderecofavorito',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enderecofavorito',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
