# Generated by Django 5.2.15 on 2026-06-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoristas', '0005_favorito_rua_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
