# Generated by Django 5.2.15 on 2026-06-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoristas', '0006_foto_utilizador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='activo',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='status_cadastro',
            field=models.CharField(choices=[('pendente', 'Pendente de análise'), ('em_analise', 'Em análise'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('suspenso', 'Suspenso')], db_index=True, default='pendente', max_length=20),
        ),
    ]
