# Generated by Django 5.2.15 on 2026-06-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoristas', '0007_alter_motorista_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='email_token',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
